### ISSUE TITLE
Algorithm written error

### ISSUE THREAD

**Issue by BryceQing** [luliyucoordinate/Leetcode#4]
The line 25 is wrong for the index should be 2:
           heapq.heappop(p)[2]

**Comment by luliyucoordinate** [comment]
which problem?

**Comment by luliyucoordinate** [comment]
> The line 25 is wrong for the index should be 2:
> heapq.heappop(p)[2]

which problem?

**Comment by Frankchen250** [comment]
23rd I remember




| |
陈忠庆
邮箱：15195893057@163.com
|

签名由 网易邮箱大师 定制

On 05/07/2019 08:19, LiYu Lu wrote:

The line 25 is wrong for the index should be 2:
heapq.heappop(p)[2]

which problem?

**Comment by BryceQing** [comment]
23rd

**Comment by BryceQing** [comment]
23rd


| |
陈忠庆
邮箱：15195893057@163.com
|

签名由 网易邮箱大师 定制

On 05/07/2019 08:18, LiYu Lu wrote:

which problem?

**Comment by luliyucoordinate** [comment]
fix it, thx
