### ISSUE TITLE
Leetcode 451部分代码有问题

### ISSUE THREAD

**Issue by Cherrymelon** [luliyucoordinate/Leetcode#7]
```
class Solution:
    def frequencySort(self, s):
        """
        :type s: str
        :rtype: str
        """
        str_map = {}
        for i in s:
            str_map[i] = str_map.get(i, 0) + 1 

        return ''.join(sorted([i for i in s], key=lambda a: str_map[a], reverse=True))
```
上面代码对用例'accdsseess'会把d和a放错，改成下面就ok了

```class Solution:
    def frequencySort(self, s):
        """
        :type s: str
        :rtype: str
        """
        str_map = {}
        for i in s:
            str_map[i] = str_map.get(i, 0) + 1 

        return ''.join(sorted(
            [i for i in s], key=lambda a: str_map[a], reverse=False))[::-1]
```

**Comment by luliyucoordinate** [comment]
> ```
> class Solution:
>     def frequencySort(self, s):
>         """
>         :type s: str
>         :rtype: str
>         """
>         str_map = {}
>         for i in s:
>             str_map[i] = str_map.get(i, 0) + 1 
> 
>         return ''.join(sorted([i for i in s], key=lambda a: str_map[a], reverse=True))
> ```
> 
> 上面代码对用例'accdsseess'会把d和a放错，改成下面就ok了
> 
> ```
>     def frequencySort(self, s):
>         """
>         :type s: str
>         :rtype: str
>         """
>         str_map = {}
>         for i in s:
>             str_map[i] = str_map.get(i, 0) + 1 
> 
>         return ''.join(sorted(
>             [i for i in s], key=lambda a: str_map[a], reverse=False))[::-1]
> ```

针对字符出现频率排序，并没有要求字典序啊~同学

**Comment by luliyucoordinate** [comment]
针对字符出现频率排序，并没有要求字典序啊~同学

**Comment by Cherrymelon** [comment]
不好意思，把类似的题设带入进去了
