### ISSUE TITLE
Leetcode 1197 异或运算相关疑问

### ISSUE THREAD

**Issue by Hanny2010** [luliyucoordinate/Leetcode#8]
大佬好，
看到csdn的[博客](https://blog.csdn.net/qq_17550379/article/details/101195668)过来的。
最后一种解法，核心点是判断是否会走到紫色点。
如果我没理解错的话，判断紫色点是用的这一行代码：
https://github.com/luliyucoordinate/Leetcode/blob/master/src/1197-Minimum-Knight-Moves/1197.py#L7

您能讲一讲这一行是什么意思吗，为啥这样写就能work？
多谢！

**Comment by pika2021** [comment]
能麻烦您讲一下不，感谢！ @luliyucoordinate

**Comment by miketom-m** [comment]
全加器（full adder）和（来自对应的英语 Sum，zh.wikipedia.ahmu.cf/wiki/加法器）再取余数（remainder，https://stackoverflow.com/questions/38922606/what-is-x-1-and-x-1）

**Comment by pika2021** [comment]
感谢解答！
